### ISSUE TITLE
why we always use img_real to train generator weights in ccGAN？

### ISSUE THREAD

**Issue by busyyang** [mafda/generative_adversarial_networks_101#5]
in ccGAN, we feed the img_real and img_fake to train the weights of discriminator. After that, we should train the generator weights. I think we should use the [masked_imgs, real] as the input and output pairs to train the generator, but you use the img_real to train that. When the input is img_real, how could generator learning anything to generate a new pic? Could you explain  the reason? thanks.

~~~py
for e in range(epochs + 1):
    for i in range(len(X_train) // batch_size):
        
        # Train Discriminator weights
        discriminator.trainable = True
        
        # Real samples
        img_real = X_train[i*batch_size:(i+1)*batch_size]
        real_labels = y_train[i*batch_size:(i+1)*batch_size]
        
        d_loss_real = discriminator.train_on_batch(x=img_real, y=[real, real_labels])
        
        # Fake Samples
        masked_imgs = mask_randomly(img_real)
        gen_imgs = generator.predict(masked_imgs)
        
        d_loss_fake = discriminator.train_on_batch(x=gen_imgs, y=[fake, fake_labels])
         
        # Discriminator loss
        d_loss_batch = 0.5 * (d_loss_real[0] + d_loss_fake[0])
        
        # Train Generator weights
        discriminator.trainable = False

        d_g_loss_batch = d_g.train_on_batch(x=img_real, y=real)     # =============> d_g_loss_batch = d_g.train_on_batch(x=masked_imgs, y=real) 
~~~

**Comment by mafda** [comment]
Hello,

Firstly, I want to express my gratitude for your patience and diligence in pointing out this issue 3 years ago. Your insight was invaluable, and I sincerely appreciate your contribution to the project.

I am writing to inform you that the problem you highlighted regarding the input for training the generator weights has been successfully [rectified](https://github.com/mafda/generative_adversarial_networks_101/blob/master/src/mnist/04_CCGAN_MNIST.ipynb). You're absolutely right in your understanding. The correct input, [masked_imgs, real], is now being utilized, enabling the generator to learn and generate new images effectively. I want to apologize for any confusion or inconvenience caused by the previous oversight.

`d_g_loss_batch = d_g.train_on_batch(x=masked_imgs, y=real)`

Thank you once again for your understanding and patience.

Best regards,
